### ISSUE TITLE
Graspness implementation checkpoints

### ISSUE THREAD

**Issue by mousecpn** [user432/gamma#2]
Hello, thanks for your brilliant work!
Is it possible to open-source the checkpoints for graspness? And then it's convenient for me to directly use it.

**Comment by mousecpn** [comment]
I found the checkpoint. Sorry for bothering you.

**Comment by zycq486** [comment]
> I found the checkpoint. Sorry for bothering you.

hi，could you tell me where do you find the checkpoint ,i only find  GSNet  ,not checkpoint for this paper

**Comment by mousecpn** [comment]
> > I found the checkpoint. Sorry for bothering you.
> 
> hi，could you tell me where do you find the checkpoint ,i only find GSNet ,not checkpoint for this paper

The checkpoint I meant is GSNet's checkpoint
